name: Build Workflow
on: [push, pull_request]

jobs:
  chain-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Build and push docker container
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./chain
          file: ./Dockerfile.ci
          push: true
          tags: odinprotocol/core:latest



