name: Chain Workflow
on: [push, pull_request]

jobs:
  chain-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./chain

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Build and push docker container
        uses: docker/build-push-action@v2
        working-directory: ${{env.working-directory}}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: ./Dockerfile.ci
          push: true
          tags: odinprotocol/core:latest



